# Generated by Django 5.0.6 on 2024-10-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='created_by',
            new_name='admin',
        ),
    ]
