# Generated by Django 5.0.6 on 2024-10-10 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('route_name', models.CharField(max_length=200)),
                ('is_visible', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to=settings.AUTH_USER_MODEL)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='roles.roles')),
                ('route_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.routetype')),
            ],
        ),
    ]
