# Generated by Django 5.0.6 on 2024-10-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
